name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Load Environment Variables
        run: echo "${{secrets.DEVELEOPMENT_SECERETS}}" > .env

      - name: Install Contentful CLI
        run: npm install -g contentful-cli

      - name: Install dependencies
        run: npm ci

      - name: Login to Contentful
        run: |
          contentful login --management-token ${{secrets.CONTENTFUL_CMA_TOKEN}} &&
          contentful space use --space-id ${{secrets.CONTENTFUL_SPACE_ID}}

      - name: Create new environment
        run: contentful space environment create --name master-2024-06-14 --environment-id master-2024-06-14

      - name: Show all spaces
        run: contentful space environment list

      - name: Build
        run: npm run build
