name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Load Environment Variables
        run: echo "${{secrets.DEVELEOPMENT_SECERETS}}" > .env

      - name: Install Contentful CLI
        run: npm install -g contentful-cli

      - name: Install dependencies
        run: npm ci

      - name: Login to Contentful
        run: |
          contentful login --management-token ${{secrets.CONTENTFUL_CMA_TOKEN}} &&
          contentful space use --space-id ${{secrets.CONTENTFUL_SPACE_ID}}

      - name: Export content model
        id: export_model
        run: |
          # Fetch the list of environments
          environments=$(contentful space environment list)

          master_environment=$(echo "$environments" | grep 'master' | sort)
          aliased_master_environment=$(echo "$master_environment" | grep 'active' | awk '{print $2}' | sed 's/\[active\]//g')

          file=$(contentful merge export --te "$aliased_master_environment" --se master-2024-06-14-13-35)
          migration_file_path=$(echo "$file" | sed -n 's/^.*exported to \(\/Users\/nextly\/migrations\/[^ ]*\)\..*$/\1/p')
          echo "::set-output name=migration_file_path::$migration_file_path"
          echo "::set-output name=aliased_master_environment::$aliased_master_environment"

      - name: Merge model changes
        run: contentful space  migration --yes --s ${{secrets.CONTENTFUL_SPACE_ID}} --e ${{ steps.export_model.outputs.aliased_master_environment }} ${{ steps.export_model.outputs.migration_file_path }}

      - name: Build
        run: npm run build
